### ISSUE TITLE
InvalidPathException from Configuration.parse on Windows

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/java-common-lib#34]
### Context
On Windows, paths typically start with a device identifier like `C:`.
This needs to be considered when handling paths in some places.

### Problem
Using a unzipped CPAchecker archive (r35978) the cmdline `.\scripts\cpa.bat -bmc E:\test\file.c`
throws an `InvalidPathException` when accessing files from the CPAchecker jar-file.

### Stacktrace
<pre>
java.nio.file.InvalidPathException: Illegal char <:> at index 3: jar:file:/C:/Users/kfrie/Downloads/CPAchecker-1.9.2-svn-35978M-windows/cpachecker.jar!/org/sosy_lab/cpachecker/util/automaton/find-target-locations.properties
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at org.sosy_lab.common.configuration.Parser.parse(Parser.java:306)
        at org.sosy_lab.common.configuration.Parser.parse(Parser.java:160)
        at org.sosy_lab.common.configuration.ConfigurationBuilder.loadFromResource(ConfigurationBuilder.java:273)
        at org.sosy_lab.cpachecker.util.automaton.TargetLocationProviderImpl.tryGetAutomatonTargetLocations(TargetLocationProviderImpl.java:58)
[...]
</pre>

I do not see this problem as part of CPAchecker.
I hope that this problem can be solved in `java-common-lib`.
It appears for different OpenJDK versions (11 and 15) on Windows 10.

**Comment by PhilippWendler** [comment]
Note that the exception message indicates that `C:` is *not* the problem, it is the occurrence of `:` in other places in the path.

The configuration system stores for each configuration option its "source" in order to be able to resolve relative paths, and this source is stored as a `Path` instance. This happens to work on other systems even if the content is not actually a valid path but a URL that points to some file in a JAR file, but here it fails.

Not sure how to solve this. We might be able to switch the source information to use a different class, but it is unclear which one (and this is part of the public API). Otherwise we might accept that resolving a relative path from a classpath resource will not work and make the source information optional.

There might also be a way to store this information as `Path` if using an URI. To find this out, please debug `ConfigurationBuilder.loadFromResource` and check whether the `try` block is executed completely or whether the `catch` block is entered, and what the values of `sourcePath` and `sourceString` are.

**Comment by kfriedberger** [comment]
- **resourceName**: find-target-locations.properties
- **source**: Resources.asByteSource(jar:file:/C:/Users/kfrie/Downloads/CPAchecker-1.9.2-svn-35978M-windows/cpachecker.jar!/org/sosy_lab/cpachecker/util/automaton/find-target-locations.properties).asCharSource(UTF-8)
- **catch exception**: java.nio.file.FileSystemNotFoundException
- **sourcePath**: null
- **sourceString**: jar:file:/C:/Users/kfrie/Downloads/CPAchecker-1.9.2-svn-35978M-windows/cpachecker.jar!/org/sosy_lab/cpachecker/util/automaton/find-target-locations.properties

**Comment by kfriedberger** [comment]
I found a working solution here: https://stackoverflow.com/a/48298758/2183882
